### ISSUE TITLE
Error: lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by sebastianbarfort** [rOpenGov/dkstat#15]
I seem to be getting an error when running the following code: 

    library("dkstat")
    aulaar_meta <- dst_meta(table = "PRIS61", lang = "da")
    aulaar <- dst_get_data(table = "PRIS61", HOVED = "Årsgennemsnit",TID = "2000", lang = "dk")

**Comment by krose** [comment]
The language parameter can only be "da" or "en". I have added a test in the function dst_get_data to make sure you get a better error message if the parameter is invalid.

```
library("dkstat")
aulaar_meta <- dst_meta(table = "PRIS61", lang = "da")
aulaar <- dst_get_data(table = "PRIS61", HOVED = "Årsgennemsnit",TID = "2000", lang = "da")
```

**Comment by sebastianbarfort** [comment]
Yes, super. Thanks!
