### ISSUE TITLE
Small error in metadata for FOLK2

### ISSUE THREAD

**Issue by Deleetdk** [rOpenGov/dkstat#18]
There is a slight error in the results returned by the metadata for this table:

```
meta_FOLK2 = dkstat::dst_meta("FOLK2", lang = "en")
v_countries = meta_FOLK2$values$IELAND$text
v_countries[str_detect(meta_FOLK2$values$IELAND$text, pattern = "South")]
[1] "South Africa "                        "South Sudan"                          "Southwest Africa"                    
[4] "South and central America not stated" "South Korea"   
```

South Africa has a space at the end.

**Comment by Deleetdk** [comment]
Apparently, DST has fixed this error now because I no longer get it.

**Comment by krose** [comment]
DST have two identical databases and they switch at 09:00 every morning. DST work on the offline version so all new statistics get published when they do the switch exactly at 9 o'clock the next day. I once tried to download a lot of tables to find fun spurious correlations and found a lot errors. I know they try to fix as many they find.

**Comment by Deleetdk** [comment]
Right now, it's a pain. The metadata for one table returns "South Africa ". This can also be used to download the data, but once you get it, it's "South Africa". This changed recently and broke my code. :(

E.g.:
```

dkstat::dst_meta("FOLK2", lang = "en")
dkstat::dst_meta("STRAFNA1", lang = "en")
```
