### ISSUE TITLE
Update Github Actions

### ISSUE THREAD

**Issue by aleksanderbl29** [rOpenGov/dkstat#32]

**Comment by aleksanderbl29** [comment]
@dieghernan I see that you have a recent fork of this repo with the same kind of changes i am doing in `32-update-github-actions`. If there's anything you find that is missing when I merge my branch, please let me know.

Also, I am planning to rename the master branch to main (out of habit / preference), so please beware of that in regards to future PRs.

**Comment by dieghernan** [comment]
Sure! So far I'll wait until you fix the tests, that's creating noise when updating the actions
